feat: get datasource tables on par with views
snowflakedb/terraform-provider-snowflake pull request #3249
Opened 2024-12-05 09:53 UTC by hpors

When using the terraform plugin we've got hindered by the discrepancy between the datasources views and tables. It seems the datasource views has already been further developed than tables. In the roadmap it is stated that the redesign for snowflake_tables is in progress, but for us this is a blocking issue, hence this MR. 
The goal of this MR is to add the new functionalities of the views datasource to tables as well. 

## Test Plan
* [ ] acceptance tests for changed datasource Tables have been changed
* [ ] integration tests for tables have been changed as filter types have been added and changed

## References
* https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/views
* https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/data-sources/tables
* https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/v1-preparations/LIST_OF_STABLE_RESOURCES_FOR_V1.md

2024-12-05 10:36 UTC, sfc-gh-asawicki commented
Hey @hpors. Thanks for contributing the the project.

Tables are being reworked currently, and their schemas may change significantly. We usually leave datasources as the last thing to do in the rework because only then do we have the proper schemas for them and it allows us to enforce just one migration when the object is fully reworked. Because of that I wouldn't merge these changes right now.

We can leave this PR open and may use it or parts of it when we have the table object fully reworked. Does that sound okay to you?

2024-12-05 12:50 UTC, hpors commented
hi @sfc-gh-asawicki, thank you for the feedback.

I understand the reasoning behind leaving the datasources until the end of the rework. I am okay with leaving this PR open and potentially using it later.

Is there any indication of the timeline for when the table object rework might be completed?

2024-12-05 16:11 UTC, sfc-gh-asawicki commented
After concluding functions, procedures, accounts, and unsafe execute - tables will become our top priority object to finish its rework. It is probably the "biggest" object, and Christmas Holidays are coming, so I would estimate that tables should be finished before the end of January.

2025-02-27 13:58 UTC, hpors commented
Little kindly bump, wondering if there is any progress on the tables?

2025-02-27 15:19 UTC, sfc-gh-asawicki commented
Hey @hpors, please check our updated roadmap: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/ROADMAP.md#feature-gap-closing---the-current-approach

2025-05-07 07:08 UTC, sfc-gh-jcieslak requested changes
Thanks for the contribution :) I left a few comments, and in some of them I would like to get @sfc-gh-asawicki input, but the rest of them could be applied now. I'll change the target branch do `dev` as we are pushing new changes there.

2025-05-07 07:08 UTC, sfc-gh-jcieslak commented on pkg/sdk/testint/tables_integration_test.go
> +		tables, err := client.Tables.Show(ctx, sdk.NewShowTableRequest().WithTerse(*sdk.Bool(true)).WithLike(sdk.Like{
change `*sdk.Bool(true)` to just `true`

2025-05-07 07:08 UTC, sfc-gh-jcieslak commented on pkg/sdk/testint/tables_integration_test.go
> +		tables, err := client.Tables.Show(ctx, sdk.NewShowTableRequest().WithStartsWith(*sdk.String(table.Name)))
Change `*sdk.String(table.Name))` to just `table.Name`

2025-05-07 10:34 UTC, sfc-gh-asawicki commented on pkg/datasources/tables.go
> +			describeOutput, err := client.Tables.DescribeColumns(ctx, sdk.NewDescribeTableColumnsRequest(table.ID()))
Let's not add all these listed options as part of this PR. We can discuss them later if needed.

2025-05-07 10:37 UTC, sfc-gh-asawicki commented on pkg/datasources/tables_acceptance_test.go
> +	externalTableName := acc.TestClient().Ids.Alpha()
Schema should be created like it was before as we want to filter by in schema inside the test (this way, we know it is the only table there)

2025-05-07 10:42 UTC, sfc-gh-asawicki requested changes
I agree with @sfc-gh-jcieslak comments.

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables.go
> +	"starts_with": {
I've updated the code to match the implementation in streams.go

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables.go
> +	if v, ok := d.GetOk("in"); ok {
I've updated the code to match the implementation in streams.go

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables.go
> +			describeOutput, err := client.Tables.DescribeColumns(ctx, sdk.NewDescribeTableColumnsRequest(table.ID()))
Am I correct to assume no changes are needed in this PR?

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables_acceptance_test.go
> +	}
I've removed these lines

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables_acceptance_test.go
> +	externalTableName := acc.TestClient().Ids.Alpha()
It's not clear to me what changes are asked to be made. Could you try to explain again?

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables_acceptance_test.go
> +		like = "%v"
updated to `%[6]s`.

2025-05-09 10:56 UTC, hpors commented on pkg/datasources/tables_acceptance_test.go
> +		starts_with = trimsuffix("%v", "%%")
Don't really think so, removed.

2025-05-09 10:56 UTC, hpors commented on pkg/schemas/table.go
> +package schemas
I'm not really sure what you mean here, should I empty/remove the file or is the file empty in your view?

2025-05-09 10:56 UTC, hpors commented on pkg/sdk/testint/tables_integration_test.go
> +		tables, err := client.Tables.Show(ctx, sdk.NewShowTableRequest().WithTerse(*sdk.Bool(true)).WithLike(sdk.Like{
Changed as requested.

2025-05-09 10:56 UTC, hpors commented on pkg/sdk/testint/tables_integration_test.go
> +		tables, err := client.Tables.Show(ctx, sdk.NewShowTableRequest().WithStartsWith(*sdk.String(table.Name)))
Changed as requested.

2025-05-12 07:38 UTC, sfc-gh-jcieslak commented on pkg/datasources/tables_acceptance_test.go
> +		like = "%v"
The `tableName+"%"` parameter is repeated twice as `fmt.Sprintf` argument, with positional string replacements one `tableName+"%"` is enough.

2025-05-12 07:43 UTC, sfc-gh-jcieslak commented on pkg/schemas/table.go
> +package schemas
It was empty in GitHub for some reason, look good now.

2025-05-12 07:52 UTC, sfc-gh-jcieslak commented on pkg/datasources/tables_acceptance_test.go
> +	externalTableName := acc.TestClient().Ids.Alpha()
So the setup of this test should be the same as before:
```Go
func TestAcc_Tables(t *testing.T) {
	_ = testenvs.GetOrSkipTest(t, testenvs.EnableAcceptance)
	acc.TestAccPreCheck(t)

	schema, schemaCleanup := acc.TestClient().Schema.CreateSchema(t)
	t.Cleanup(schemaCleanup)

	tableId := acc.TestClient().Ids.RandomSchemaObjectIdentifierInSchema(schema.ID())
	stageId := acc.TestClient().Ids.RandomSchemaObjectIdentifierInSchema(schema.ID())
	externalTableId := acc.TestClient().Ids.RandomSchemaObjectIdentifierInSchema(schema.ID())
// the rest of the test...
}
```
**and**
The `PreCheck:                 func() { acc.TestAccPreCheck(t) },` could be also reverted.

The rest looks good other than test configuration, but I left a separate comment there.

2025-05-12 07:58 UTC, sfc-gh-jcieslak commented on pkg/datasources/tables.go
> +			describeOutput, err := client.Tables.DescribeColumns(ctx, sdk.NewDescribeTableColumnsRequest(table.ID()))
Yeah, this is something we'll add later, but one thing could be considered (cc: @sfc-gh-asawicki ). Because there are two describe options, I would rename two field names in the schema:
- `with_describe` -> `with_describe_column`
- `describe_output` -> `describe_column_output`

This would be to clearly separate two versions of the `DESC TABLE` command.

2025-05-13 07:25 UTC, hpors commented on pkg/datasources/tables.go
> +			describeOutput, err := client.Tables.DescribeColumns(ctx, sdk.NewDescribeTableColumnsRequest(table.ID()))
I don't think I agree with this change in the current PR. All objects currently use the `resources.DescribeOutputAttributeName` to add the describe_output to their schema. This would mean creating a separate one for a possible change in the future. I personally would change both renaming and adding the other version in another PR.

2025-05-13 07:29 UTC, hpors commented on pkg/datasources/tables_acceptance_test.go
> +	externalTableName := acc.TestClient().Ids.Alpha()
I think I know where the confusion originates from. The PR originally stems from the `cd4a9148d3e8c08325e50cdd106373e50c820708` commit, which had the setup I worked with in the acceptance tests file. I now moved to the test setup in the `73ad5d9f8563993730899ecf4c6d0aff324da445` commit and updated where needed.

2025-05-13 13:22 UTC, sfc-gh-jcieslak commented on pkg/datasources/tables.go
> +			describeOutput, err := client.Tables.DescribeColumns(ctx, sdk.NewDescribeTableColumnsRequest(table.ID()))
Right, let's leave the names as they are right now

2025-05-13 13:27 UTC, sfc-gh-jcieslak approved these changes

2025-05-13 19:35 UTC, hpors commented
Rebased with dev and fixed all mentions from graphite-app

2025-05-14 10:54 UTC, sfc-gh-jcieslak approved these changes

2025-05-14 10:54 UTC, sfc-gh-jcieslak commented on docs/data-sources/tables.md
> +Datasource used to get details of filtered tables. Filtering is aligned with the current possibilities for [SHOW TABLES](https://docs.snowflake.com/en/sql-reference/sql/show-tables) query (only `like
More than like is supported

2025-05-15 08:54 UTC, sfc-gh-jmichalak commented on docs/data-sources/tables.md
> +Datasource used to get details of filtered tables. Filtering is aligned with the current possibilities for [SHOW TABLES](https://docs.snowflake.com/en/sql-reference/sql/show-tables) query (only `like
This line is generated based on `Description` in https://github.com/snowflakedb/terraform-provider-snowflake/blob/ab271a2c74fbda048715a0651fa41dfc7a988b19/pkg/datasources/tables.go#L60. 

What is the exact result of `make pre-push`? We run it in our CI, so after this command, we expect changes related only to the modified files.

2025-05-16 06:08 UTC, hpors commented on docs/data-sources/tables.md
> +Datasource used to get details of filtered tables. Filtering is aligned with the current possibilities for [SHOW TABLES](https://docs.snowflake.com/en/sql-reference/sql/show-tables) query (only `like
I've updated the Description and run `make pre-push` again. I had to revert changes to files `docs/resources/primary_connection.md` and `docs/resources/secondary_connection.md` as it changed `snowflake_primary_connection ` to `snowflakeprimaryconnection ` and `snowflake_secondary_connection` to `snowflakesecondaryconnection.

2025-05-16 07:12 UTC, sfc-gh-jmichalak approved these changes

2025-05-19 14:19 UTC, sfc-gh-jcieslak approved these changes

2025-05-19 14:21 UTC, sfc-gh-asawicki approved these changes

2025-05-19 14:21 UTC, merged