chore: Adjust test asserts
snowflakedb/terraform-provider-snowflake pull request #3289
Opened 2024-12-13 15:06 UTC by sfc-gh-jcieslak

TBD

2024-12-18 11:34 UTC, sfc-gh-asawicki commented on pkg/acceptance/bettertestspoc/assert/resourceassert/account_resource_gen.go
> +func (a *AccountResourceAssert) HasAdminNameEmpty() *AccountResourceAssert {
let's filter out the needed messages by the "required" attribute in schema - e.g. this can never be empty, so this assertion should not be generated

2025-02-21 12:45 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resourceassert/account_resource_gen.go
> +func (a *AccountResourceAssert) HasAdminNameEmpty() *AccountResourceAssert {
Done

2025-02-24 14:05 UTC, sfc-gh-asawicki requested changes

2025-02-24 14:05 UTC, sfc-gh-asawicki commented on pkg/acceptance/bettertestspoc/config/providermodel/gen/main/main.go
> +				details.AdditionalStandardImports = slices.DeleteFunc(details.AdditionalStandardImports, func(dep string) bool { return dep == "encoding/json" })
it is ugly, please add a comment to the description (we have somewhere a TODO not to reuse directly between the model types)

2025-02-24 14:05 UTC, sfc-gh-asawicki commented on pkg/internal/genhelpers/mappers.go
> +	PrintToString      = func(field string) string { return fmt.Sprintf(`fmt.Sprintf("%%v", %s)`, field) }
nit: PrintToString vs ToString below (from the name its hard to distinguish them)

2025-02-24 14:33 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/objectassert/gen/templates/assertions.tmpl
> +        {{ $functionParameterType = printf "...%s" (TypeWithoutSlice .ConcreteType) }}
Chose the second approach.

2025-02-24 14:34 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resource_parameter_assertions.go
> +package assert
Done

2025-02-24 14:34 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resource_show_assertions.go
> +package assert
Done

2025-02-24 14:37 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/gen/model.go
> +func MapToResourceShowOutputAssertion(field genhelpers.Field) (ResourceShowOutputAssertionModel, bool) { // TODO: Temporary
It was added some time ago, but I'm guessing I wanted to change the way additional import ("fmt" in this case) is returned. I can either remove the TODO and leave it as is or adjust the return type to []string and return additional imports as slice of packages.

2025-02-24 14:55 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/user_show_output_ext.go
> -package resourceshowoutputassert
Done

2025-02-24 14:55 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/config/providermodel/gen/main/main.go
> +				details.AdditionalStandardImports = slices.DeleteFunc(details.AdditionalStandardImports, func(dep string) bool { return dep == "encoding/json" })
Added a TODO and adjust the Jira

2025-02-24 15:00 UTC, sfc-gh-jcieslak commented on pkg/internal/genhelpers/mappers.go
> +	PrintToString      = func(field string) string { return fmt.Sprintf(`fmt.Sprintf("%%v", %s)`, field) }
Changed to `ConvertToString` and groupped string mappers to be closer to each other

2025-02-24 15:05 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/objectassert/connection_snowflake_gen.go
> +		for _, want := range expected {
I think the test conditions you gave won't pass. We iterate over expected (abb), then use slices.Contains func on actual to see if abb is somewhere there. If not, a new error is appended and then returned with errors.Join(errs...). Tbh I wanted to use slices.Equal and it works most of the time, but some the types are not comparable which makes them not usable with slices.Equal. I tried to distinguish comparable types in generator, but it seemed to be impossible or just hard enough to sit with it whole day.

2025-02-24 15:06 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/objectassert/function_snowflake_gen.go
> +		return errors.Join(errs...)
I'm not sure if we care about repetition in generated code, but it could be a lot shorter with slices.Equal, but read the explanation above.

2025-02-24 15:09 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/objectassert/gen/model.go
> +	}
which one?

2025-02-24 15:11 UTC, sfc-gh-jcieslak commented on pkg/acceptance/bettertestspoc/assert/resourceshowoutputassert/gen/model.go
> +		imports = append(imports, "fmt")
still not sure what should we extract

2025-08-06 11:18 UTC, closed without merging